# Generated by Django 5.2.7 on 2025-10-26 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('SELECTED', 'Selected'), ('REJECTED_AFTER_INTERVIEW', 'Rejected After Interview'), ('HOLD', 'Hold'), ('ACCEPTED', 'Accepted'), ('CONFIRMED', 'Confirmed')], default='NEW', max_length=24)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='api.jobrequest')),
            ],
        ),
    ]
